### ISSUE TITLE
Improving the Readme.md file 

### ISSUE THREAD

**Issue by JatinPawar** [Mazbaul/Event_reservation#1]
I would like to improve the readme.md file so as to give information about the project i.e. what is the main agenda, how it is to be installed,etc.
Can i work on it?

**Comment by Mazbaul** [comment]
readme updated

**Comment by Mazbaul** [comment]
follow the instruction in readme file to set up.if any problem comment

**Comment by JatinPawar** [comment]
Thank You sir.
